DEFAULT_BASE_URL = "https://chatjimmy.ai"
DEFAULT_MODEL = "llama3.1-8B"
DEFAULT_TOP_K = 8
TOKEN_LIMIT = 6144
MAX_ATTACHMENT_SIZE = 50 * 1024  # 50KB
STATS_DELIMITER_START = "<|stats|>"
STATS_DELIMITER_END = "<|/stats|>"
